ud-cis-discord/Sage

src/commands/configuration/addcourse.ts, src/commands/partial visibality question/private.ts, src/commands/partial visibality question/sudoreply.ts, src/commands/staff/warn.ts, src/lib/types/Course.d.ts
Changes include
- warn command
- pv question embed footer tweaks
- separate channel for private questions
=> Minor changes from meeting on 1-19

src/commands/assign.ts, src/commands/staff/mute.ts
removed a comment in assign.ts
=> added mute.ts

package-lock.json, package.json, src/pieces/report.ts
=> Report emails

.vscode/settings.json, src/commands/info/discordstatus.ts, src/commands/info/info.ts, src/lib/utils.ts
Also minor tweaks to info command
=> Discord status cmd

src/commands/partial visibality question/reply.ts, src/commands/staff/warn.ts, src/pieces/logs/modLog.ts, src/pieces/logs/serverLog.ts, src/pieces/report.ts, tsconfig.json
=> Misc changes

src/commands/info/roleinfo.ts, src/lib/utils.ts
=> refactor: changed sendToHastebin to sendToFile

config.example.ts, src/commands/info/feedback.ts
=> feat: feedback command.

src/commands/configuration/addcourse.ts, src/commands/info/roleinfo.ts, src/pieces/messageCount.ts
closes #70
closes #72
closes #73
=> 2.0.1 changes

src/commands/check.ts, src/commands/configuration/enroll.ts
=> 2.0.2/misc changes

src/commands/assign.ts, src/commands/configuration/enroll.ts, src/commands/partial visibality question/anonymous.ts, src/commands/partial visibality question/private.ts
=> tweak: sort corse and assign list order closes #86

src/commands/configuration/addcourse.ts, src/commands/configuration/enroll.ts, src/commands/partial visibality question/anonymous.ts, src/commands/partial visibality question/private.ts, src/commands/question tagging/addassignment.ts, src/commands/question tagging/question.ts
=> tweak: make course names always lowercase

src/pieces/logs/serverLog.ts
=> fix the serverlog

src/commands/submit.ts
=> feat: submit command closes #82

src/commands/admin/announce.ts, src/commands/configuration/addcourse.ts, src/commands/partial visibality question/anonymous.ts, src/commands/partial visibality question/private.ts, src/lib/arguments.ts
closes #93
closes #94
closes #95
=> Various tweaks

onboard/nudge.ts, package.json
This is the nudge script, it nudges all unverified users to verify.
=> feat: nudge script

src/pieces/verification.ts
=> feat: Added ability for users to re-verify.

src/pieces/logs/memberLog.ts
It should:tm: get rid of those errors in the error log
=> fix: Role update exector not found error

src/pieces/logs/modLog.ts
=> fix: Times are in ms not in seconds.

src/commands/admin/disable.ts, src/commands/admin/enable.ts, src/commands/admin/showcommands.ts, src/commands/admin/sudo.ts, src/commands/info/help.ts, src/commands/submit.ts, src/lib/types/Command.d.ts, src/pieces/commandManager.ts
Also adds the `sudo` command to bypass the disabled check as well as permissions and location checks.
=> Adds the ability to enable and disable commands on the fly.

src/commands/info/leaderboard.ts
=> Leaderboard

.vscode/settings.json, config.example.ts, package-lock.json, package.json, src/commands/remind.ts, src/commands/reminders/cancelreminder.ts, src/commands/reminders/remind.ts, src/commands/reminders/viewreminders.ts, src/lib/types/Reminder.d.ts, src/lib/utils.ts, src/pieces/remind.ts
Three commands and a brand new piece
closes #113
=> Reminders are here

src/commands/admin/announce.ts, src/lib/arguments.ts
Also fixes the channel args parser when there is 0 matching channels found
=> Allows messages in the announce command to contain pipes

src/pieces/report.ts
=>  Use system time for report cron

config.example.ts, src/commands/admin/activity.ts, src/commands/admin/disable.ts, src/commands/admin/enable.ts, src/commands/admin/sudo.ts, src/lib/types/Command.d.ts, src/lib/types/SageData.d.ts, src/pieces/commandManager.ts, src/sage.ts
Sages status and command enabled/disabled status persistence through reboots.  Also, the current version number is appended to Sages status for thirty seconds on initial boot. This is nice for when Jenkins boots Sage up for us.
Closes #152
=> Reboot Persistance

src/commands/fun/xkcd.ts
=> fix: XKCD cmd with too long footer

src/lib/types/errors.ts, src/lib/utils.ts, src/pieces/blacklist.ts, src/pieces/commandManager.ts, src/pieces/logs/errorLog.ts, src/pieces/logs/memberLog.ts, src/pieces/logs/modLog.ts, src/pieces/logs/serverLog.ts, src/pieces/messageCount.ts, src/pieces/remind.ts, src/pieces/report.ts, src/pieces/roleHandler.ts, src/pieces/verification.ts, src/sage.ts
=> feat: Error log now exists in exactly one place

src/commands/admin/commit.ts, src/commands/fun/f.ts
=> Fix commit and F commands

autodoc/movemd.sh
=> Pulled before pushing command changes

src/commands/admin/setassign.ts, src/lib/utils.ts, src/pieces/commandManager.ts
=> fix: people can now not enroll in a course twice

src/commands/fun/latex.ts
Old:
New:
The new one is worse, but it's just a backup. Hopefully the old service gets brought back online soon....
=> fix: latex command uses backup API

src/commands/info/leaderboard.ts, src/pieces/commandManager.ts, src/pieces/messageCount.ts
- automatic leaderboard paging
- a "thank you" message check - Sage will react with steve_peace if any message contains "thank" and "Sage"
- correct the command name in the level up message
=> Leveluphotfix

src/commands/fun/poll.ts
=> prevent dupe options for poll

src/commands/admin/addbutton.ts, src/pieces/commandManager.ts, src/pieces/memberHandler.ts, src/pieces/verification.ts
new modal for hash
buttons can now be added to a Sage message
buttonHandler added to commandManager
=> full verification revamp

src/commands/info/info.ts, src/pieces/messageCount.ts, src/pieces/report.ts
- fix typo in /info
- fix exp detracting when on level 1 with 0 exp
- admins get full course report every week (untested unfortunately)
=> fixes for info, messageCount, report

src/commands/partial visibility question/private.ts, src/pieces/databaseSync.ts
- fix: private questions can only be opened in enrolled courses
=> database sync

src/commands/admin/removecourse.ts
- added to /removecourse, not its own command
=> Purge Staff Role from Course Staff
